version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: njxzc-blog:latest
    ports:
      - '3002:3000'
    volumes:
      - './posts:/app/posts/'
    restart: always