version: '3.8'

services:
  app:
    image: jaya2021/simple-blog-njxzc:latest
    ports:
      - '3000:3000'
    volumes:
      - './posts:/app/posts/'
      - './config.js:/app/config.js'
    restart: always
